# LLMS Used for inferencing
- model_name: base
  model_id: hf.co/bartowski/Llama-3.2-3B-Instruct-GGUF:Q5_K_S
  url: https://huggingface.co/bartowski/Llama-3.2-3B-Instruct-GGUF
- model_name: sql_coder
  model_id: hf.co/TheBloke/sqlcoder-GGUF:Q4_K_S
  url: https://huggingface.co/TheBloke/sqlcoder-GGUF
- model_name: python_coder
  model_id: hf.co/TheBloke/CodeLlama-7B-Python-GGUF:Q4_K_M
  url: https://huggingface.co/TheBloke/CodeLlama-7B-Python-GGUF
- model_name: memgraph_coder
  model_id: hf.co/ragraph-ai/stable-cypher-instruct-3b:Q4_K_M
  url: https://huggingface.co/ragraph-ai/stable-cypher-instruct-3b
- model_name: thinking_agent
  model_id: hf.co/bartowski/openai_gpt-oss-120b-GGUF:Q8_0
  url: https://huggingface.co/bartowski/openai_gpt-oss-120b-GGUF
